<a href="https://colab.research.google.com/github/antussa2016/Acodes2021/blob/main/BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("/content/drive/MyDrive/@agriffini_.csv")

In [6]:
df.head(5)

twitter_id                 date  \
0  1126371613480501248  2019-05-09 06:21:34   
1  1123693128588910597  2019-05-01 20:58:13   
2  1120675817628028928  2019-04-23 13:08:30   
3  1119523737332797445  2019-04-20 08:50:33   
4  1114887549653270530  2019-04-07 13:48:00   

                                               tweet  
0  b'For some strange reason there is among many ...  
1  b'"Your washing machine is equipped with a sop...  
2  b"@ivandorna @NotEnoughNews @IntesaSP_Help L'a...  
3  b'@IntesaSP_Help Inoltre, sempre in occasione ...  
4  b'RT @linkibol: ssh-keygen -t rsa -b 4096 http...

In [7]:
df['tweet']

0      b'For some strange reason there is among many ...
1      b'"Your washing machine is equipped with a sop...
2      b"@ivandorna @NotEnoughNews @IntesaSP_Help L'a...
3      b'@IntesaSP_Help Inoltre, sempre in occasione ...
4      b'RT @linkibol: ssh-keygen -t rsa -b 4096 http...
                             ...                        
766    b'I hate shiny monitors!  http://twitpic.com/2...
767    b"Hmmm... it tastes good, so either is unhealt...
768    b'The dark side of mobile http://twitpic.com/2...
769            b'This is a test... http://bit.ly/c1Ib8M'
770    b'Requesting an invite for Tweetboard Alpha (h...
Name: tweet, Length: 771, dtype: object

In [8]:
df.shape

(771, 3)

In [9]:
df['tweet'] =  df['tweet'].str.replace('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', ' ')
df['tweet'] = df['tweet'].str.replace(r"[\"\'\|\?\=\.\@\#\*\,]", '')

<ipython-input-9-ce70c6032ee1>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['tweet'] =  df['tweet'].str.replace('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', ' ')
<ipython-input-9-ce70c6032ee1>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df['tweet'] = df['tweet'].str.replace(r"[\"\'\|\?\=\.\@\#\*\,]", '')


In [10]:
!pip install tensorflow-text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 26.0 MB/s eta 0:00:00


In [11]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [12]:
processed_texts = [text.lower().split() for text in df['tweet']]
processed_texts

[['bfor',
  'some',
  'strange',
  'reason',
  'there',
  'is',
  'among',
  'many',
  'programmers',
  'a',
  'confusion',
  'between',
  'advanced',
  'and',
  'convoluted',
  'solutions\\xe2\\x80\\xa6'],
 ['byour',
  'washing',
  'machine',
  'is',
  'equipped',
  'with',
  'a',
  'sophisticated',
  'system',
  'that',
  'will',
  'delay',
  'the',
  'spin',
  'cycle',
  'if',
  'the',
  'load',
  'is',
  'not',
  'per\\xe2\\x80\\xa6'],
 ['bivandorna',
  'notenoughnews',
  'intesasp_help',
  'lapplicazione',
  'web',
  'mostra',
  'in',
  'console',
  'un',
  'errore',
  '`post\\xe2\\x80\\xa6'],
 ['bintesasp_help',
  'inoltre',
  'sempre',
  'in',
  'occasione',
  'della',
  'pasqua',
  'sara\\',
  'impossibile',
  'accedere',
  'al',
  'banking',
  'online',
  'per',
  'un',
  'erro\\xe2\\x80\\xa6'],
 ['brt', 'linkibol:', 'ssh-keygen', '-t', 'rsa', '-b', '4096'],
 ['brt',
  'develer:',
  'inaugurazione',
  'della',
  'nuova',
  'sede',
  'di',
  'develer',
  'pi\\xc3\\xb9',
  'spaz

In [13]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [14]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

get_sentence_embeding([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.8435169 , -0.51327264, -0.88845724, ..., -0.74748874,
        -0.75314736,  0.91964483],
       [-0.8720836 , -0.5054398 , -0.9444668 , ..., -0.85847515,
        -0.7174535 ,  0.88082975]], dtype=float32)>

In [15]:
text = []

for i in df['tweet']:
    string = ""
    for j in i:
        string += j
    text.append(string)

text[2]

'bivandorna NotEnoughNews IntesaSP_Help Lapplicazione web mostra in console un errore `POST\\xe2\\x80\\xa6  '

In [16]:
bert_text = text[:200]
#len(text[:100])
bert_text

['bFor some strange reason there is among many programmers a confusion between advanced and convoluted Solutions\\xe2\\x80\\xa6  ',
 'bYour washing machine is equipped with a sophisticated system that will delay the spin cycle if the load is not per\\xe2\\x80\\xa6  ',
 'bivandorna NotEnoughNews IntesaSP_Help Lapplicazione web mostra in console un errore `POST\\xe2\\x80\\xa6  ',
 'bIntesaSP_Help Inoltre sempre in occasione della pasqua sara\\ impossibile accedere al banking online per un Erro\\xe2\\x80\\xa6  ',
 'bRT linkibol: ssh-keygen -t rsa -b 4096  ',
 'bRT develer: Inaugurazione della nuova sede di Develer Pi\\xc3\\xb9 spazio per un futuro in crescita!\\n\\ninnovation developers software embedded\\xe2\\x80\\xa6',
 'bRT naufraghi: Wait arent they \\xf0\\x9f\\x98\\x81  ',
 'bRT DannyDutch: Im secure enough in my stupidness to admit I initially thought this was a picture of dinosaurs  ',
 'bRT develer: Oggi al QtDay2019! QtDay  ',
 'bRT cvtsi2sd: Come atto di protesta contro il Famil

In [17]:
bert_embed = get_sentence_embeding(bert_text)
bert_embed


<tf.Tensor: shape=(200, 768), dtype=float32, numpy=
array([[-0.8145234 , -0.4298686 , -0.9403021 , ..., -0.89740956,
        -0.67548156,  0.86221397],
       [-0.716104  , -0.23452236, -0.34997702, ..., -0.455906  ,
        -0.45744973,  0.6860249 ],
       [-0.7475367 , -0.36458993, -0.5695952 , ..., -0.36077675,
        -0.65688646,  0.78650314],
       ...,
       [-0.6597619 , -0.19358833,  0.31799632, ...,  0.358031  ,
        -0.47058356,  0.7103881 ],
       [-0.8331255 , -0.30925673, -0.7068248 , ..., -0.35312843,
        -0.5922982 ,  0.84152824],
       [-0.68745565, -0.42704856, -0.9466045 , ..., -0.8679361 ,
        -0.5807394 ,  0.683038  ]], dtype=float32)>

In [25]:
import sklearn
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(bert_embed)

array([[0.99999976, 0.7833797 , 0.9191151 , ..., 0.6088418 , 0.94698286,
        0.9867361 ],
       [0.7833797 , 1.0000002 , 0.9245675 , ..., 0.9034351 , 0.88101596,
        0.7554002 ],
       [0.9191151 , 0.9245675 , 0.9999999 , ..., 0.8483443 , 0.98303187,
        0.89106584],
       ...,
       [0.6088418 , 0.9034351 , 0.8483443 , ..., 1.0000002 , 0.7942242 ,
        0.57523715],
       [0.94698286, 0.88101596, 0.98303187, ..., 0.7942242 , 1.0000002 ,
        0.9283508 ],
       [0.9867361 , 0.7554002 , 0.89106584, ..., 0.57523715, 0.9283508 ,
        1.        ]], dtype=float32)

In [18]:
df['encode']=''
df.head(5)

twitter_id                 date  \
0  1126371613480501248  2019-05-09 06:21:34   
1  1123693128588910597  2019-05-01 20:58:13   
2  1120675817628028928  2019-04-23 13:08:30   
3  1119523737332797445  2019-04-20 08:50:33   
4  1114887549653270530  2019-04-07 13:48:00   

                                               tweet encode  
0  bFor some strange reason there is among many p...         
1  bYour washing machine is equipped with a sophi...         
2  bivandorna NotEnoughNews IntesaSP_Help Lapplic...         
3  bIntesaSP_Help Inoltre sempre in occasione del...         
4          bRT linkibol: ssh-keygen -t rsa -b 4096

In [26]:
df['encode'][0]=cosine_similarity(bert_embed)

<ipython-input-26-609788ac092b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['encode'][0]=cosine_similarity(bert_embed)


In [27]:
df.head(1)

twitter_id                 date  \
0  1126371613480501248  2019-05-09 06:21:34   

                                               tweet  \
0  bFor some strange reason there is among many p...   

                                              encode  
0  [[0.99999976, 0.7833797, 0.9191151, 0.8439301,...